Expression assertion
zendframework/zend-permissions-acl pull request #23
Opened 2016-07-16 14:45 UTC by nikolaposa

I think it would be useful to have possibility for defining assertions in this way, as those can be very easily persisted or serialized in contrast to `CallbackAssertion` for example. Also, having such dynamic and generic type of assertion is much more convenient when it comes to creating some permissions CRUD functionality.

## Example usage
```php
ExpressionAssertion::fromArray([
    'left' => [ExpressionAssertion::OPERAND_CONTEXT_PROPERTY => 'role.username'],
    'operator' => '=',
    'right' => 'test',
]);

ExpressionAssertion::fromArray([
    'left' => [ExpressionAssertion::OPERAND_CONTEXT_PROPERTY => 'role.age'],
    'operator' => '>',
    'right' => 20,
]);

ExpressionAssertion::fromArray([
    'left' => [ExpressionAssertion::OPERAND_CONTEXT_PROPERTY => 'role.adult'], //resolves to isAdult() or getAdult() method on Role object
    'operator' => '=',
    'right' => true,
]);

ExpressionAssertion::fromArray([
    'left' => [ExpressionAssertion::OPERAND_CONTEXT_PROPERTY => 'resource.short_description'], //resolves to either getShortDescription() method or short_description property
    'operator' => 'regex',
    'right' => '/ipsum/',
]);
```

2018-05-01 21:44 UTC, weierophinney requested changes

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +    const OPERATOR_NIN = 'nin';
I think this one would make more sense as `!in`, making it more akin to `!=`. I'll make that change on merge.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +    private $assertContext = [];
This should be removed. `assert()` should pass the context to methods that need it.

The reason is concurrency. In async systems, if this value gets reset in another process, it can affect the operands in the current process. By passing it around instead, the context of the current process can never be changed.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +    private function __construct($left, $operator, $right)
There really needs to be documentation of what constitutes valid operands.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +     */
This should indicate exceptions that can be thrown by `validateOperand()` and `validateOperator()`.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +     * @return self
Same comment here, and also indicate the more specific exception this method raises.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +        return $this->evaluate();
As noted above, do not memoize the context, but instead pass it on as an argument.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +        $right = $this->getRightValue();
If this method receives the context, it would then pass it to the above two methods.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +        return $this->resolveOperandValue($this->left);
And this method, and the `getRightValue()` method, would pass the context on to `resolveOperandValue()`.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +                if (!isset($this->assertContext[$objectName])) {
Once we get here, this line (and others in this method) would instead reference the context passed to the method.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +            return $object->$accessor();
The above could be more simply written as:

```php
if (method_exists($object, $accessor)) {
    return $object->accessor();
}
```

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +            throw new \RuntimeException('Object property cannot be resolved');
Why are you using a global exception case here, versus the package-specific one elsewhere?

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +                return $left != $right;
Out of curiousity, why are these using the non-strict forms? Do you think we should have additional operators for strict in/equality?

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +                ));
Technically, there is no possible way to get to the default case, as you've validated the operator previously.

2018-05-01 21:44 UTC, weierophinney commented on src/Assertion/ExpressionAssertion.php
> +        if (!property_exists($object, $field)) {
This doesn't do what you think it does. Or, rather, it has an unintentional side-effect you may not be aware of.

Starting in PHP 5.3, `property_exists` started returning true _regardless of visibility_. This means that the above will return `true` _even if the property is not public_. Which makes line 227 a potential error. The only way to solve this is via reflection.

2018-05-01 21:46 UTC, weierophinney commented
I've incorporated all feedback in #36; I would have pushed to your branch, but you've locked it. :smile:

2018-05-02 06:32 UTC, webimpress commented
@weierophinney It can be closed now, as #36 is merged and 2.7.0 is released.

2018-05-02 13:28 UTC, closed without merging